LIKE = '//*[@id="content"]/div/div[1]/div/main/div[1]/div/div/div[1]/div/div[2]/div[4]/button'
DISLIKE = '//*[@id="content"]/div/div[1]/div/main/div[1]/div/div/div[1]/div/div[2]/div[2]/button'

allow_location_button = '//*[@id="modal-manager"]/div/div/div/div/div[3]/button[1]'
not_interested_button = '//*[@id="modal-manager"]/div/div/div/div/div[3]/button[2]'
not_interested_during_swipe = '//*[@id="modal-manager"]/div/div/div[2]/button[2]'
back_to_matching_button = '//*[@id="modal-manager-canvas"]/div/div/div[1]/div/div[3]/button'
gold_maybe_later_button = '//*[@id="modal-manager"]/div/div/div/div[3]/button[2]'
login_button = '//*[@id="content"]/div/div[1]/div/main/div[1]/div/div/header/div[1]/div[2]/div/button'
login_continue_button = '//*[@id="modal-manager"]/div/div/div[1]/button'
accept_cookies = '//*[@id="content"]/div/div[2]/div/div/div[1]/button'
main_image = '//*[@id="content"]/div/div[1]/div/main/div[1]/div/div/div[1]/div/div[1]/div[3]/div[1]/div[1]/span[1]/div'
google_login_button = '//*[@id="modal-manager"]/div/div/div[1]/div/div[3]/span/div[1]/div/button'
google_email_input = '//*[@id="identifierId"]'
google_password_input = '//*[@id="password"]/div[1]/div/div[1]/input'